language: go

go:
 - 1.3

install:
 - go get github.com/onsi/ginkgo/ginkgo
 - go get github.com/onsi/gomega
 - go get github.com/smartystreets/goconvey/convey

notifications:
  email: false